x-lagoon-project:
  # Lagoon project name (leave `&lagoon-project` when you edit this)
  &lagoon-project testbed

x-volumes:
  &default-volumes # Define all volumes you would like to have real-time mounted into the docker containers
  volumes:
    - .:/app:delegated ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.

x-environment: &default-environment
  LAGOON_PROJECT: *lagoon-project
  # Route that should be used locally, if you are using pygmy, this route *must* end with .docker.amazee.io
  LAGOON_ROUTE: &default-url http://${COMPOSE_PROJECT_NAME:-testbed}.ddev.site
  # Uncomment if you like to have the system behave like in production
  #LAGOON_ENVIRONMENT_TYPE: production
  # Uncomment to enable xdebug and then restart via `docker-compose up -d`
  # XDEBUG_ENABLE: "true"

x-user:
  &default-user # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
  user: "1000"

services:
  nginx:
    image: uselagoon/nginx-drupal:latest
    labels:
      lagoon.type: nginx-php
      # lagoon.persistent: /app/web/sites/default/files/ # define where the persistent storage should be mounted too
      lagoon.resources.requests.cpu: 20m
      lagoon.resources.limits.cpu: 200m
      lagoon.resources.requests.memory: 200Mi
      lagoon.resources.limits.memory: 1Gi
      lagoon.resources.override-branch.main.requests.cpu: 21m
      lagoon.resources.override-branch.main.limits.cpu: 201m
      lagoon.resources.override-branch.main.requests.memory: 201Mi
      lagoon.resources.override-branch.main.limits.memory: 1001Mi
      lagoon.resources.override-branch.test1.requests.cpu: 22m
      lagoon.resources.override-branch.test1.limits.cpu: 202m
      lagoon.resources.override-branch.test1.requests.memory: 202Mi
      lagoon.resources.override-branch.test1.limits.memory: 1002Mi
    <<: [*default-volumes, *default-user]
    environment:
      <<: *default-environment # loads the defined environment variables from the top
      LAGOON_LOCALDEV_URL: *default-url

  php:
    image: uselagoon/php-8.2-fpm:latest
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx # we want this service be part of the nginx pod in Lagoon
      # lagoon.persistent: /app/web/sites/default/files/ # define where the persistent storage should be mounted too
      lagoon.resources.requests.cpu: 50m
      lagoon.resources.limits.cpu: 1
      lagoon.resources.requests.memory: 300Mi
      lagoon.resources.limits.memory: 2Gi
      lagoon.resources.override-branch.main.requests.cpu: 51m
      lagoon.resources.override-branch.main.limits.cpu: 1.01
      lagoon.resources.override-branch.main.requests.memory: 301Mi
      lagoon.resources.override-branch.main.limits.memory: 2001Mi
      lagoon.resources.override-branch.test1.requests.cpu: 52m
      lagoon.resources.override-branch.test1.limits.cpu: 1.02
      lagoon.resources.override-branch.test1.requests.memory: 302Mi
      lagoon.resources.override-branch.test1.limits.memory: 2002Mi

    <<: [*default-volumes, *default-user]
    environment:
      <<: *default-environment # loads the defined environment variables from the top
